### ISSUE TITLE
blang/latex-docker

### ISSUE THREAD

**Issue by blang** [bermeitinger-b/fedora-docker-latex#1]
You might want to try [blang/latex-docker](https://github.com/blang/latex-docker)

**Comment by bermeitinger-b** [comment]
I've been using it for a long time now but the latexmk version is too old. It doesn't build my project `unsupported argument -pdflua`

**Comment by blang** [comment]
Have you tried the rather new `blang/latex:ctanfull` image? The latest tag covers the ubuntu version which is quite old, `ctanfull` is less than a month old

**Comment by bermeitinger-b** [comment]
Huh, yes I thought so. The image is quite big, so using it in CI might be complicated. But it works, thanks!

**Comment by blang** [comment]
You might want to customize `blang/latex:ctanbasic` to your needs, but of course that can be a lot of work to only include packages needed. Good luck!
